-- Excluded coins
INSERT INTO public.excluded_coins(id_cryptocompare) VALUES (542140); --MED, inactive
INSERT INTO public.excluded_coins(id_cryptocompare) VALUES (731516); -- PXS, fout la merde


-- Manual reddit lookup
INSERT INTO social_infos_manual VALUES (4337,'Betacoin');
INSERT INTO social_infos_manual VALUES (4345,'myriadcoin');
INSERT INTO social_infos_manual VALUES (4346,'MoonCoin');
INSERT INTO social_infos_manual VALUES (4350,'energycoin');
INSERT INTO social_infos_manual VALUES (4403,'Bitmark');
INSERT INTO social_infos_manual VALUES (4437,'Earthcoin');
INSERT INTO social_infos_manual VALUES (4524,'FeatherCOin');
INSERT INTO social_infos_manual VALUES (4562,'MintCoin');
INSERT INTO social_infos_manual VALUES (4571,'NavCoin');
INSERT INTO social_infos_manual VALUES (4574,'netcoin');
INSERT INTO social_infos_manual VALUES (4587,'potcoin');
INSERT INTO social_infos_manual VALUES (4592,'reddCoin');
INSERT INTO social_infos_manual VALUES (4618,'SysCoin');
INSERT INTO social_infos_manual VALUES (5017,'vericoin');
INSERT INTO social_infos_manual VALUES (5019,'whitecoin');
INSERT INTO social_infos_manual VALUES (5032,'Stealthcoin');
INSERT INTO social_infos_manual VALUES (5285,'nem');
INSERT INTO social_infos_manual VALUES (5295,'NuBits');
INSERT INTO social_infos_manual VALUES (5300,'BitBay');
INSERT INTO social_infos_manual VALUES (5305,'theblocknet');
INSERT INTO social_infos_manual VALUES (5313,'thefaircoin');
INSERT INTO social_infos_manual VALUES (5315,'GuldenCoin');
INSERT INTO social_infos_manual VALUES (5325,'florincoin');
INSERT INTO social_infos_manual VALUES (5338,'AppleByteMe');
INSERT INTO social_infos_manual VALUES (5343,'boolberry');
INSERT INTO social_infos_manual VALUES (5348,'FoldingCoin');
INSERT INTO social_infos_manual VALUES (5349,'SolarCoin');
INSERT INTO social_infos_manual VALUES (5370,'NeosCoin');
INSERT INTO social_infos_manual VALUES (5374,'pinkcoin');
INSERT INTO social_infos_manual VALUES (6103,'nexusearth');
INSERT INTO social_infos_manual VALUES (7586,'Crowncoin');
INSERT INTO social_infos_manual VALUES (8761,'SproutsCryptocurrency');
INSERT INTO social_infos_manual VALUES (17857,'OKcash');
INSERT INTO social_infos_manual VALUES (18180,'Voxelus_Official');
INSERT INTO social_infos_manual VALUES (20157,'GameCreditsCrypto');
INSERT INTO social_infos_manual VALUES (20198,'DBIX');
INSERT INTO social_infos_manual VALUES (20591,'ionomy');
INSERT INTO social_infos_manual VALUES (20655,'thehempcoin');
INSERT INTO social_infos_manual VALUES (20745,'Aeon');
INSERT INTO social_infos_manual VALUES (21365,'dimecoin');
INSERT INTO social_infos_manual VALUES (22015,'RiseVision');
INSERT INTO social_infos_manual VALUES (22325,'muecoin');
INSERT INTO social_infos_manual VALUES (22329,'Bitsend');
INSERT INTO social_infos_manual VALUES (24294,'stratisplatform');
INSERT INTO social_infos_manual VALUES (25721,'Decentplatform');
INSERT INTO social_infos_manual VALUES (26132,'komodoplatform');
INSERT INTO social_infos_manual VALUES (27996,'BlockSafeFoundation');
INSERT INTO social_infos_manual VALUES (28276,'Coval');
INSERT INTO social_infos_manual VALUES (30022,'zcoin');
INSERT INTO social_infos_manual VALUES (30736,'ByteBall');
INSERT INTO social_infos_manual VALUES (35030,'POSW');
INSERT INTO social_infos_manual VALUES (35678,'BeyondTheVoidGame');
INSERT INTO social_infos_manual VALUES (40811,'pascalcoin');
INSERT INTO social_infos_manual VALUES (44003,'paccoin');
INSERT INTO social_infos_manual VALUES (55540,'AugmentorsGame');
INSERT INTO social_infos_manual VALUES (55650,'MobileGo');
INSERT INTO social_infos_manual VALUES (61138,'darcrus');
INSERT INTO social_infos_manual VALUES (66270,'taasfund');
INSERT INTO social_infos_manual VALUES (72438,'Humaniq');
INSERT INTO social_infos_manual VALUES (78152,'aragonproject');
INSERT INTO social_infos_manual VALUES (107672,'BATProject');
INSERT INTO social_infos_manual VALUES (127667,'QRL');
INSERT INTO social_infos_manual VALUES (129013,'ecc');
INSERT INTO social_infos_manual VALUES (130939,'lykke');
INSERT INTO social_infos_manual VALUES (137013,'statusim');
INSERT INTO social_infos_manual VALUES (139467,'civicplatform');
INSERT INTO social_infos_manual VALUES (141171,'iXledger');
INSERT INTO social_infos_manual VALUES (141331,'dentcoin');
INSERT INTO social_infos_manual VALUES (141464,'ethos_io');
INSERT INTO social_infos_manual VALUES (166548,'MonacoCard');
INSERT INTO social_infos_manual VALUES (166594,'numerai');
INSERT INTO social_infos_manual VALUES (171390,'ecobit');
INSERT INTO social_infos_manual VALUES (171986,'Tether');
INSERT INTO social_infos_manual VALUES (172091,'RaiBlocks');
INSERT INTO social_infos_manual VALUES (175618,'ATBcoin');
INSERT INTO social_infos_manual VALUES (177139,'CoinDash');
INSERT INTO social_infos_manual VALUES (177175,'district0x');
INSERT INTO social_infos_manual VALUES (177863,'santiment');
INSERT INTO social_infos_manual VALUES (179164,'MetalPay');
INSERT INTO social_infos_manual VALUES (179926,'suncontract');
INSERT INTO social_infos_manual VALUES (179990,'RialtoAI');
INSERT INTO social_infos_manual VALUES (180013,'OpenANX');
INSERT INTO social_infos_manual VALUES (180804,'encrypgen');
INSERT INTO social_infos_manual VALUES (184163,'LAToken');
INSERT INTO social_infos_manual VALUES (184298,'PillarProject');
INSERT INTO social_infos_manual VALUES (185669,'investFeedOfficial');
INSERT INTO social_infos_manual VALUES (185695,'PropyInc');
INSERT INTO social_infos_manual VALUES (186277,'0xProject');
INSERT INTO social_infos_manual VALUES (186335,'CossIO');
INSERT INTO social_infos_manual VALUES (186875,'stormtoken');
INSERT INTO social_infos_manual VALUES (188352,'voise');
INSERT INTO social_infos_manual VALUES (191142,'tauchain');
INSERT INTO social_infos_manual VALUES (194567,'BlockCat');
INSERT INTO social_infos_manual VALUES (198408,'Mothershipexchange');
INSERT INTO social_infos_manual VALUES (198710,'viberate');
INSERT INTO social_infos_manual VALUES (198983,'bitcore_btx');
INSERT INTO social_infos_manual VALUES (199148,'decentraland');
INSERT INTO social_infos_manual VALUES (220204,'Agrello');
INSERT INTO social_infos_manual VALUES (222085,'Neblio');
INSERT INTO social_infos_manual VALUES (225277,'CentraTech');
INSERT INTO social_infos_manual VALUES (194883,'Everex');
INSERT INTO social_infos_manual VALUES (234811,'cobinhood');
INSERT INTO social_infos_manual VALUES (235213,'atlantio');
INSERT INTO social_infos_manual VALUES (236358,'uTrustPlatform');
INSERT INTO social_infos_manual VALUES (238733,'ambrosus');
INSERT INTO social_infos_manual VALUES (247232,'NewYorkCoin');
INSERT INTO social_infos_manual VALUES (283116,'EnjinCoin');
INSERT INTO social_infos_manual VALUES (292748,'etherparty');
INSERT INTO social_infos_manual VALUES (296844,'worldcore');
INSERT INTO social_infos_manual VALUES (299397,'waltonchain');
INSERT INTO social_infos_manual VALUES (307219,'RipioCreditNetwork');
INSERT INTO social_infos_manual VALUES (310297,'eidoo');
INSERT INTO social_infos_manual VALUES (310497,'kybernetwork');
INSERT INTO social_infos_manual VALUES (310829,'Tronix');
INSERT INTO social_infos_manual VALUES (311558,'Maecenas');
INSERT INTO social_infos_manual VALUES (311829,'DomRaider');
INSERT INTO social_infos_manual VALUES (314580,'SALTLending');
INSERT INTO social_infos_manual VALUES (318169,'loopring');
INSERT INTO social_infos_manual VALUES (318199,'hcash');
INSERT INTO social_infos_manual VALUES (319075,'ObsidianProject');
INSERT INTO social_infos_manual VALUES (319130,'clearpoll');
INSERT INTO social_infos_manual VALUES (322002,'YOYOW');
INSERT INTO social_infos_manual VALUES (322963,'cryptobismuth');
INSERT INTO social_infos_manual VALUES (324068,'helloicon');
INSERT INTO social_infos_manual VALUES (326222,'FlashCoins');
INSERT INTO social_infos_manual VALUES (327500,'PayPie');
INSERT INTO social_infos_manual VALUES (328639,'Metaverse_Blockchain');
INSERT INTO social_infos_manual VALUES (331603,'Alis');
INSERT INTO social_infos_manual VALUES (335059,'RequestNetwork');
INSERT INTO social_infos_manual VALUES (335127,'Aeon');
INSERT INTO social_infos_manual VALUES (335505,'datumnetwork');
INSERT INTO social_infos_manual VALUES (336538,'VibeHub');
INSERT INTO social_infos_manual VALUES (337162,'AirSwap');
INSERT INTO social_infos_manual VALUES (338070,'Cindicator');
INSERT INTO social_infos_manual VALUES (338335,'enigmacatalyst');
INSERT INTO social_infos_manual VALUES (338541,'WAX_io');
INSERT INTO social_infos_manual VALUES (338555,'AirToken');
INSERT INTO social_infos_manual VALUES (339617,'PowerLedger');
INSERT INTO social_infos_manual VALUES (341267,'RedPulseToken');
INSERT INTO social_infos_manual VALUES (341328,'zeusshield');
INSERT INTO social_infos_manual VALUES (345420,'revain_org');
INSERT INTO social_infos_manual VALUES (345510,'modum_io');
INSERT INTO social_infos_manual VALUES (350048,'BlueCrypto');
INSERT INTO social_infos_manual VALUES (351720,'LUXCoin');
INSERT INTO social_infos_manual VALUES (360827,'DovuTokenSale');
INSERT INTO social_infos_manual VALUES (361881,'Electroneum');
INSERT INTO social_infos_manual VALUES (369132,'Simple_Token');
INSERT INTO social_infos_manual VALUES (369151,'streamr');
INSERT INTO social_infos_manual VALUES (374031,'PUREaltcoin');
INSERT INTO social_infos_manual VALUES (374281,'blockmason');
INSERT INTO social_infos_manual VALUES (380712,'decentbet');
INSERT INTO social_infos_manual VALUES (381189,'LIFEtoken');
INSERT INTO social_infos_manual VALUES (382450,'CredoToken');
INSERT INTO social_infos_manual VALUES (385907,'GridPlus');
INSERT INTO social_infos_manual VALUES (385952,'genesisvision');
INSERT INTO social_infos_manual VALUES (388042,'MercuryProtocol');
INSERT INTO social_infos_manual VALUES (388145,'Soarcoin');
INSERT INTO social_infos_manual VALUES (389849,'minexcoin');
INSERT INTO social_infos_manual VALUES (402714,'QASH');
INSERT INTO social_infos_manual VALUES (408849,'Flixxo');
INSERT INTO social_infos_manual VALUES (411620,'mywish');
INSERT INTO social_infos_manual VALUES (412112,'Autonio');
INSERT INTO social_infos_manual VALUES (418778,'ETHLend');
INSERT INTO social_infos_manual VALUES (419814,'SHIELDCOIN');
INSERT INTO social_infos_manual VALUES (422188,'CryptoBridge');
INSERT INTO social_infos_manual VALUES (429355,'Oyster');
INSERT INTO social_infos_manual VALUES (431413,'DiviProject');
INSERT INTO social_infos_manual VALUES (446372,'Achain_Official');
INSERT INTO social_infos_manual VALUES (449573,'SocialSend');
INSERT INTO social_infos_manual VALUES (517477,'GIFTO');
INSERT INTO social_infos_manual VALUES (517483,'TimeNewBank');
INSERT INTO social_infos_manual VALUES (517896,'lockchainco');
INSERT INTO social_infos_manual VALUES (531426,'MobileGo');
INSERT INTO social_infos_manual VALUES (542140,'MediBloc');
INSERT INTO social_infos_manual VALUES (543363,'Bounty0x');
INSERT INTO social_infos_manual VALUES (586088,'DeepBrainChain');
INSERT INTO social_infos_manual VALUES (166503,'eos');
INSERT INTO social_infos_manual VALUES (597629,'itcofficial');
INSERT INTO social_infos_manual VALUES (639943,'SportyFi');
INSERT INTO social_infos_manual VALUES (543502,'breadwallet');
INSERT INTO social_infos_manual VALUES (571314,'aelfblockchain');
INSERT INTO social_infos_manual VALUES (4440,'einsteinium');
INSERT INTO social_infos_manual VALUES (5296,'monacoin');
INSERT INTO social_infos_manual VALUES (20681,'SaluS');
INSERT INTO social_infos_manual VALUES (20594,'safex');
INSERT INTO social_infos_manual VALUES (23728,'steem');
INSERT INTO social_infos_manual VALUES (25921,'ICONOMI');
INSERT INTO social_infos_manual VALUES (29010,'nolimitcoin');
INSERT INTO social_infos_manual VALUES (35953,'enigmacatalyst');
INSERT INTO social_infos_manual VALUES (42598,'XSPEC');
INSERT INTO social_infos_manual VALUES (43044,'Ubiq');
INSERT INTO social_infos_manual VALUES (71077,'TokenCard');
INSERT INTO social_infos_manual VALUES (136211,'Veritasium');
INSERT INTO social_infos_manual VALUES (136269,'SkycoinProject');
INSERT INTO social_infos_manual VALUES (176280,'Rivetz');
INSERT INTO social_infos_manual VALUES (185689,'BitClave');
INSERT INTO social_infos_manual VALUES (186331,'Presearch');
INSERT INTO social_infos_manual VALUES (195018,'nolimitcoin');
INSERT INTO social_infos_manual VALUES (202330,'Bitcoincash');
INSERT INTO social_infos_manual VALUES (218008,'BytomBlockchain');
INSERT INTO social_infos_manual VALUES (218107,'Asch_Platform');
INSERT INTO social_infos_manual VALUES (306304,'cappasity');
INSERT INTO social_infos_manual VALUES (309621,'Chainlink');
INSERT INTO social_infos_manual VALUES (318154,'ExperiencePoints');
INSERT INTO social_infos_manual VALUES (355702,'dragonchain');
INSERT INTO social_infos_manual VALUES (360063,'Tokensnet');
INSERT INTO social_infos_manual VALUES (362769,'XenonXnn');
INSERT INTO social_infos_manual VALUES (598428,'HTMLCOIN');
INSERT INTO social_infos_manual VALUES (619555,'nebulas');
INSERT INTO social_infos_manual VALUES (659770,'GXS');
INSERT INTO social_infos_manual VALUES (675053,'hpbcoin');
INSERT INTO social_infos_manual VALUES (679566,'HiveProject_net');
INSERT INTO social_infos_manual VALUES (685098,'ecc');
INSERT INTO social_infos_manual VALUES (116180,'ZenSys');
INSERT INTO social_infos_manual VALUES (360299,'selfkey');
INSERT INTO social_infos_manual VALUES (368694,'ATMChain');
INSERT INTO social_infos_manual VALUES (179896,'populous_platform');
INSERT INTO social_infos_manual VALUES (4433,'vergecurrency');
INSERT INTO social_infos_manual VALUES (347235,'BitcoinGoldHQ');

--top cryptos
insert into top_cryptos(id_cryptocomparename) values (1182);
insert into top_cryptos(id_cryptocomparename) values (3808);
insert into top_cryptos(id_cryptocomparename) values (5038);
insert into top_cryptos(id_cryptocomparename) values (24854);
insert into top_cryptos(id_cryptocomparename) values (4614);
insert into top_cryptos(id_cryptocomparename) values (5285);
insert into top_cryptos(id_cryptocomparename) values (19745);
insert into top_cryptos(id_cryptocomparename) values (20333);
insert into top_cryptos(id_cryptocomparename) values (27368);
insert into top_cryptos(id_cryptocomparename) values (112392);
insert into top_cryptos(id_cryptocomparename) values (127356);
insert into top_cryptos(id_cryptocomparename) values (171986);
insert into top_cryptos(id_cryptocomparename) values (187440);
insert into top_cryptos(id_cryptocomparename) values (202330);
insert into top_cryptos(id_cryptocomparename) values (236131);
insert into top_cryptos(id_cryptocomparename) values (299774);
insert into top_cryptos(id_cryptocomparename) values (310829);
insert into top_cryptos(id_cryptocomparename) values (321992);
insert into top_cryptos(id_cryptocomparename) values (324068);
insert into top_cryptos(id_cryptocomparename) values (5031);
insert into top_cryptos(id_cryptocomparename) values (7605);
insert into top_cryptos(id_cryptocomparename) values (5324);
insert into top_cryptos(id_cryptocomparename) values (172091);
insert into top_cryptos(id_cryptocomparename) values (347235);
insert into top_cryptos(id_cryptocomparename) values (3807);
insert into top_cryptos(id_cryptocomparename) values (166503);

insert into process_description (process_name, description) values ('DataImporter -cpd', 'Update coins list and prices');
insert into process_description (process_name, description) values ('DataImporter -o', 'Update OHLCV information (periods of 1 hour)');
insert into process_description (process_name, description) values ('DataImporter -r', 'Update Reddit statistics (number of subscribers)');
insert into process_description (process_name, description) values ('DataImporter -g', 'Update global infos (global market cap, 24h volumes)');
insert into process_description (process_name, description) values ('DataImporter -s', 'Update social stats (information relatives to twitter, Reddit linked to one cryptocurrency)');
insert into process_description (process_name, description) values ('DataImporter -hp', 'Update price historic');
insert into process_description (process_name, description) values ('DataImporter -ath', 'Update higher & lower for each cryptocurrency');
insert into process_description (process_name, description) values ('AlgoKPI -v', 'Calcul kpi related to volumes');
insert into process_description (process_name, description) values ('AlgoKPI -r', 'Calcul kpi related to reddit subscribers');
insert into process_description (process_name, description) values ('DataImporter -gt', 'Update data related to Google Trend');
insert into process_description (process_name, description) values ('AlgoKPI -gt', 'Calcul kpi related to Google Trend');
insert into process_description (process_name, description) values ('AlgoKPI -g', 'Calcul kpi related to global data');


INSERT INTO public.alert_type(
	id_alert_type, global_alert, category_type, filter_type,  trigger_period_hour, description)
	VALUES (1, false, 'price', 'TOP100', '1', '[Crypto Top 100][1h price variation > 10%] #crypto_name# (#crypto_symbol#): #val1_double#%');

