-- User: dbuser
-- DROP USER dbuser;

CREATE USER dbuser WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

ALTER USER dbuser WITH PASSWORD 'algocryptos';

GRANT postgres TO dbuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dbuser